---
title: "model description"
author: "Justin Pomeranz"
date: "1/26/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

# Model overview

Assume there are habitat patches, x, located across a landscape. Within each patch, three species may exist. A basal species B, a consumer species C, and a predator species P. In the absence of predation, the basal species population abundance is assumed to grow exponentially to to some population level, K, (logistic growth) based on some characteristic of the habitat patch (i.e. environmental condition, patch size). 

The consumer species (also know as the intraguild prey) receives all of its energy from the basal species. The consumer species population varies in direct proportion to the density of B, following a type II functional response (Holling's disk equation). The consumer species is also predated upon by the predator species, P. 

The predator species consumes both B and C, and responds to each following a type II functional response. 

## Dispersal

The model starts with some initial nonzero population abundances for all three species in each patch. First, dispersal from all patches is accounted for. The number of emmigrants, E, for each species from each patch is estimated, Then, the number of emmigrants from patch i is divided into immigrants, I, for each patch j. The likelihood of an individual dispersal from patch i to j declines exponentially with increasing distance from patch i to j. 

## Predation

After dispersal, continuous predation occurs. The number of prey *i* eaten by consumer *j*, *W_{ij}*, in a season is calculated as:

$$W_{ij} = \frac{\alpha_{ij}  N_{i}  N_{j}} {\beta_{ij}  N_{j} + N_{i}}$$

where *N_{i}* is the population abundance of resource *i*, *N_{j}* is the population abundance of consumer *i*, and $\alpha_{ij}$ and $\beta_{ij}$ are coefficients describing the functional response as the ratio of resources to consumers increases.  $\beta_{ij}$ describes how fast the predation curve reaches the asymptote of the type II functional response, and $\frac{\alpha}{\beta}$ determines the location of the asymptote. 

The total number of Basal species individual eaten is the sum of the individuals eaten by C and P:
$$W_{B} = W_{BC} +W_{CP} $$
## Survival

After accounting for predation, the remaining individuals are reduced by the base survival probability:


$$
B' = S_{0}(B - W_{B})\\
C' = S_{0}(C - W_{CP})\\
P' = S_{0}P 
$$

## Reproduction

Finally, those individuals remaining ($X_{i}'$) reproduce according to the following:
$$
B_{t+1} = \frac{r_{max}}{1 + bB'}B'\\
C_{t+1} = \frac{e_{bc} \alpha_{bc} B }{ \beta_{bc} C + B}C'\\
P_{t+1} = \left(\frac{e_{bp} \alpha_{bp} B } {\beta_{bp}P +B} +
\frac{e_{bp} \alpha_{bp} C}{\beta_{bp}P + C}\right) P'
$$

where $r_{max}$ is the maximum per-capita reproduction rate of the basal species and $b = \frac{r_{max} - 1}{K}$ determines the asymptotic relationship of population growth, where K is carrying capacity. In the absence of predation, population growth of the basal species follows a logistic growth relationship. Note the use of $X_{i}$ in determining the predation effects (terms inside of the parentheses) and $X_{i}'$ to estimate reproduction in the next generation. This can be viewed as a time lag, which incorporates continuous predation through the season, and synchronous reproduction only for the surviving individuals. 

For the consumer species (C and P) the product of $e_{ij}\alpha_{ij}$ is the maximum reproductive rate of consumer *j* on resource *i*. The carying capacity of consumer *j* on resource *i* is $\frac{N_{i}(e_{ij}\alpha_{ij} - 1)} {\beta_{ij}}$ when N_{i} is constant 

## Time t + 1

To ensure that the number of individuals in time t + 1 is an integer and to include stochasticity in our model, the population abundance for t + 1 is drawn from a Poisson distribution:
$$X_{i} \sim \text{Poisson}(\lambda_{i})$$

where 
$$\lambda_{i} = B_{t+1}, C_{t+1}, P_{t+1}$$ 

## Disturbance

We also include a disturbance probability $\mathrm{p}_{disturbance}$ which reduces the abundance of each species present in patch x at time i by some constant value (e.g., if disturbance occurs, populations are reduced by 50%)

## Resource extinction

An explicit assumption of our model is that the presence of a consumer is dependent on the presence of at least one of its' resources. Therefore, if the population abundance of B is equal to 0 at the beginning of a timestep, we force the abundances of C and P to also equal zero. Note that C and P can become locally extinct and the simulation will continue as normal, and any secondary extinctions are the direct result of trophic dynamics. 